config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  get 'up' => 'rails/health#show', as: :rails_health_check

  namespace :api do
    namespace :v1 do
      resources :example, only: [:index, :show]
      namespace :meta_data do
        get 'tags'
      end
    end
  end

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  available_locales = -> { I18n.available_locales.map(&:to_s).join('|') }
  scope '(:locale)', locale: Regexp.new(available_locales.call) do
    namespace :auth do
      get 'sign-in'
      get 'sign-up'
    end

    get 'share/:id' => 'share#index', as: :share

    resources :profiles, only: [:index, :show]

    namespace :writer do
      namespace :stories do
        get 'all'
      end
      resources :stories, except: [:show] do
        member do
          patch :order
          patch :unpublish_all
        end
        resources :chapters, except: [:new, :show] do
          member do
            patch :order
            patch :publish
            patch :unpublish
          end
        end
      end
    end

    resources :stories, only: [:index, :show] do
      resources :chapters, only: [:show] do
        member do
          get :rephrase
          get :translate
          get :rephrase_alt
          get :summarize
        end
        resources :comments, except: [:update] do
          get :reply
        end
      end
    end

    root 'home#index'
  end
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :primary_genre, class_name: :Genre
  belongs_to :secondary_genre, class_name: :Genre, optional: true
  belongs_to :author, class_name: :User

  has_many :chapters, -> { order(position: :asc) }, dependent: :destroy
  has_one_attached :cover_image, dependent: :destroy

  acts_as_taggable_on :tags
  acts_as_list scope: [:author_id], add_new_at: :top

  validates :name,
            :author,
            :primary_genre_id,
            :description,
            :cover_image,
            :tag_list,
            :language_code,
            presence: true

  scope :with_published, -> { where(chapters: { published: true }).distinct }

  def number_of_published
    chapters.where(published: true).count
  end

  def number_of_draft
    chapters.where(published: false).count
  end

  def views
    chapters.sum(:views)
  end

  def genres
    genres = [primary_genre.name]
    genres |= [secondary_genre.name] if secondary_genre
    genres
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.includes([:author, :chapters, { cover_image_attachment: :blob }, :primary_genre, :secondary_genre]).with_published
    @pagy, @stories = pagy(@stories)
  end

  def show
    @story = Story.includes([:chapters]).find(params[:id])
  end
end

app/controllers/writer/chapters_controller.rb
class Writer::ChaptersController < ApplicationController
  before_action :prepare_story
  before_action :prepare_chapter, except: [:create]

  layout 'writer/chapter'

  def index
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update('writer-content', partial: 'writer/stories/chapters')
        ]
      end
    end
  end

  def edit
    @toolbar_title = @story.name
  end

  def create
    authorize @story, policy_class: Writer::StoryPolicy
    chapter = @story.chapters.create
    redirect_to edit_writer_story_chapter_path(story_id: @story.id, id: chapter.id)
  end

  def order
    @chapter.insert_at(params[:position].to_i)
    head :ok
  end

  def publish
    @chapter.update(published: true)
    redirect_back(fallback_location: root_path)
  end

  def unpublish
    @chapter.update(published: false)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @chapter.destroy
    if params[:replace]
      replace_chapter_id = @chapter.lower_item&.id || @chapter.higher_item&.id
      return redirect_to action: :edit, story_id: @chapter.story_id, id: replace_chapter_id if replace_chapter_id

      return redirect_to edit_writer_story_path(@story)
    end
    redirect_back(fallback_location: root_path)
  end

  def update
    @chapter.update(chapter_params)

    respond_to do |format|
      format.json { render json: @chapter }
      format.html { redirect_back(fallback_location: root_path, notice: t('writer_stories.update.success')) }
    end
  end

  private

  def chapter_params
    params.require(:chapter).permit(:title, :content, :heading_image)
  end

  def prepare_story
    @story = Story.find(params[:story_id])
  end

  def prepare_chapter
    @chapter = Chapter.find(params[:id])
    authorize @chapter, policy_class: Writer::ChapterPolicy
  end
end

app/controllers/writer/stories_controller.rb
class Writer::StoriesController < ApplicationController
  include TaggableHelper

  before_action :auth_user
  before_action :prepare_story, except: [:new, :create, :index, :all]
  before_action :set_updatable, only: [:edit, :update]
  before_action :set_edit_title, only: [:edit, :update]
  before_action :set_new_title, only: [:new, :create]

  layout 'writer/editor', except: [:index, :order, :destroy]

  def index
    @my_stories = current_user.stories.includes(:chapters).with_published
  end

  def all
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update('workspace-main', partial: 'main', locals: { my_stories: current_user.stories.includes(:chapters) })
        ]
      end
    end
  end

  def new
    @story = Story.new
  end

  def create
    result = StoryService::Creator.call(params: story_params, author: current_user)
    payload = result.payload
    @story = payload[:story]

    if result.success?
      redirect_to edit_writer_story_chapter_path(story_id: @story.id, id: payload[:chapter].id)
    else
      flash.now[:alert] = result.errors
      render :new, status: :unprocessable_entity
    end
  end

  def order
    @story.insert_at(params[:position].to_i)
    head :ok
  end

  def unpublish_all
    @story.chapters.update_all(published: false)
    redirect_back(fallback_location: root_path)
  end

  def edit; end

  def update
    result = StoryService::Updater.call(params: story_params, story: @story)

    if result.success?
      redirect_to edit_writer_story_path, notice: t('writer_stories.update.success')
    else
      flash.now[:alert] = result.errors
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @story.destroy
      redirect_to writer_stories_path, notice: t('writer_stories.destroy.success')
    else
      redirect_to writer_stories_path, alert: t('writer_stories.destroy.failure')
    end
  end

  private

  def story_params
    params.require(:story).permit(:name, :description, :cover_image, :primary_genre_id, :secondary_genre_id, :tag_list, :language_code)
  end

  def prepare_story
    @story = Story.find(params[:id])
    authorize @story, policy_class: Writer::StoryPolicy
  end

  def set_updatable
    @updatable = true
  end

  def set_new_title
    @toolbar_title = t('writer_toolbar.title')
  end

  def set_edit_title
    @toolbar_title = t('writer_toolbar.editable_title')
  end

  def auth_user
    unless user_signed_in?
      flash[:info] = t('auth.not_signed_in')
      redirect_to root_path
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/writer/chapters_helper.rb
module Writer::ChaptersHelper
  def published_class(chapter)
    chapter.published ? 'next-btn' : 'save-btn'
  end
end

app/helpers/writer/stories_helper.rb
module Writer::StoriesHelper
  def fake_languages_with_codes
    [
      { code: 'en', language: 'English' },
      { code: 'fr', language: 'Français' },
      { code: 'it', language: 'Italiano' },
      { code: 'de', language: 'Deutsch' },
      { code: 'es', language: 'Español' },
      { code: 'pt', language: 'Português' },
      { code: 'ca', language: 'Català' },
      { code: 'vi', language: 'Tiếng Việt' },
      { code: 'fil', language: 'Filipino' },
      { code: 'id', language: 'Bahasa Indonesia' },
      { code: 'ms', language: 'Bahasa Melayu' },
      { code: 'th', language: 'ภาษาไทย' },
      { code: 'ru', language: 'Русский' },
      { code: 'ro', language: 'Română' },
      { code: 'tr', language: 'Türkçe' },
      { code: 'cs', language: 'Česky' },
      { code: 'pl', language: 'Polski' },
      { code: 'hu', language: 'Magyar' },
      { code: 'el', language: 'ελληνικά' },
      { code: 'et', language: 'Eesti' },
      { code: 'lv', language: 'Latviešu' },
      { code: 'lt', language: 'Lietuvių' },
      { code: 'bs', language: 'Босански' },
      { code: 'sr', language: 'Српски' },
      { code: 'hr', language: 'Hrvatski' },
      { code: 'bg', language: 'Български' },
      { code: 'sk', language: 'Slovenčina' },
      { code: 'sl', language: 'Slovenščina' },
      { code: 'be', language: 'Беларускі' },
      { code: 'uk', language: 'Українська' },
      { code: 'sv', language: 'Svenska' },
      { code: 'no', language: 'Norsk' },
      { code: 'fi', language: 'Suomi' },
      { code: 'da', language: 'Dansk' },
      { code: 'nl', language: 'Nederlands' },
      { code: 'is', language: 'Íslenska' },
      { code: 'zh-cn', language: '简体中文' },
      { code: 'zh-tw', language: '繁體中文' },
      { code: 'ja', language: '日本語' },
      { code: 'ko', language: '한국어' },
      { code: 'ar', language: 'العربية' },
      { code: 'gu', language: 'ગુજરાતી' },
      { code: 'he', language: 'עברית' },
      { code: 'hi', language: 'हिन्दी' },
      { code: 'ml', language: 'മലയാളം' },
      { code: 'or', language: 'ଓଡ଼ିଆ' },
      { code: 'fa', language: 'فارسی' },
      { code: 'pa', language: 'ਪੰਜਾਬੀ' },
      { code: 'as', language: 'অসমীয়া' },
      { code: 'bn', language: 'বাংলা' },
      { code: 'ta', language: 'தமிழ்' },
      { code: 'sw', language: 'Kiswahili' },
      { code: 'af', language: 'Afrikaans' },
      { code: 'mr', language: 'मराठी' },
      { code: 'other', language: 'Other' }
    ]
  end

  def fake_languages
    fake_languages_with_codes.map { |lang| [lang[:language], lang[:code]] }
  end

  def format_my_stories(my_stories)
    my_stories.map do |story|
      {
        id: story.id,
        title: story.name,
        language: story.language_code,
        description: story.description,
        cover: story.cover_image,
        updated: story.updated_at.strftime('%b %d, %Y'),
        is_published: story.number_of_published.positive?,
        published: story.number_of_published,
        draft: story.number_of_draft,
        views: '1M',
        comments: '10K'
      }
    end
  end

  def format_chapters(story)
    story.chapters.map do |chapter|
      {
        id: chapter.id,
        title: chapter.title,
        updated: chapter.updated_at.strftime('%b %d, %Y'),
        published: chapter.published,
        views: chapter.views,
        comments: 0
      }
    end
  end

  def updatable_content(updatable)
    updatable ? 'content hidden' : 'content'
  end

  def optional_story_title(story)
    story[:name].nil? || story[:name].empty? ? t('writer_toolbar.untitled_story') : story[:name]
  end

  def optional_chapter_title(chapter)
    chapter[:title].nil? || chapter[:title].empty? ? t('writer_toolbar.untitled_chapter') : chapter[:title]
  end
end

app/views/writer/stories/_chapters.slim
.chapters
  .create-group
    = link_to writer_story_chapters_path(story), data: { turbo_method: :post }, class: 'create-btn' do
      = mi.shape(:add).round.md_18
      = t('chapter_status.new_part')

  .sortable-list data-controller='sortable' data-sortable-url==order_writer_story_chapter_path(story_id: story.id, id: ':id')
    - format_chapters(story).map do |chapter|
      .sortable-item data-id==chapter[:id]
        .drag-indicator
          = mi.shape(:drag_indicator)
        .sortable-story
          .story-wrapper
            .story-info
              = link_to edit_writer_story_chapter_path(story_id: story.id, id: chapter[:id]) do
                strong.chapter-name == optional_chapter_title(chapter)
              .chapter-info
                .chapter-status
                  - if chapter[:published]
                    strong.publish = t('chapter_status.published')
                  - else
                    strong.draft = t('chapter_status.draft')
                  span -
                  small = chapter[:updated]
                .chapter-analysis
                  .analysis-info
                    = mi.shape(:visibility).css_class('analysis-icon')
                    = chapter[:views]
                  .analysis-info
                    = mi.shape(:comment).css_class('analysis-icon')
                    = chapter[:comments]
          .story-action
            .action-group
              .dropdown
                .action-btn
                  = mi.shape(:more_horiz).css_class('action-btn-icon')
                .dropdown-list
                  = link_to writer_story_chapter_path(story_id: story.id, id: chapter[:id]), class: 'dropdown-item', data: { turbo_method: :delete, turbo_confirm: t('confirmation.chapters.delete') } do
                    = mi.shape(:delete).md_18.css_class('action-btn-icon')
                    = t('writer_space.delete')
                  - if chapter[:published]
                    = link_to unpublish_writer_story_chapter_path(story_id: story.id, id: chapter[:id]), data: { turbo_method: :patch }, class: 'dropdown-item'
                      = mi.shape(:unpublished).md_18.css_class('action-btn-icon')
                      = t('writer_space.unpublish')
                  button.dropdown-item
                    = mi.shape(:visibility).md_18.css_class('action-btn-icon')
                    = t('writer_space.view_as_reader')

app/views/writer/stories/_editable_form.slim
= simple_form_for story, url: url, html: { multipart: true, class: 'new-story', id: 'newStoryForm', autocomplete: 'off' }, defaults: { input_html: { class: 'story-input' }, label_html: { class: 'story-label' } }, data: { controller: 'writer-navigation' } do |f|
  .story-cover.dropzone.dropzone-default.dz-clickable data-controller='dropzone' data-dropzone-max-file-size='5' data-dropzone-max-files='1' data-dropzone-accepted-files='image/jpg,image/png,image/jpeg'

    - if story.cover_image.attached?
      #preview-info data-dropzone-preview-image==url_for(story.cover_image) data-dropzone-preview-filename==story.cover_image.blob.filename data-dropzone-preview-filesize==story.cover_image.blob.byte_size

    .added-info
      = mi.shape(:wallpaper).md_48
      .notice = t('new-story-form.add_cover')
    = f.input :cover_image, label: false, input_html: { data: { dropzone_target: 'input' }, hidden: true, disabled: true, direct_upload: true }

  .story-details
    - if @updatable
      .navigation
        .nav-btn data-writer-navigation-target='contentBtn' data-action='click->writer-navigation#showContent'
          = t('new-story-form.navigation.story_details')
        .nav-btn.active data-writer-navigation-target='chaptersBtn' data-action='click->writer-navigation#showChapters'
          = t('new-story-form.navigation.table_of_contents')

    div[data-writer-navigation-target='content' class== updatable_content(@updatable)]
      .info-wrapper
        = f.input :name, label: t('new-story-form.title'), input_html: { placeholder: t('new-story-form.untitled_story') }

      .info-wrapper
        = f.input :description, as: :text, label: t('new-story-form.description'), input_html: { class: 'story-input description', rows: 5 }

      hr
      .info-wrapper
        span.story-label = t('new-story-form.genres')
        .genres-info
          .genres-wrapper
            = f.input :primary_genre_id, collection: all_genres, label: t('new-story-form.primary'), label_html: { class: false }
          .genres-wrapper
            = f.input :secondary_genre_id, collection: all_genres, include_blank: true, label: t('new-story-form.secondary'), label_html: { class: false }

      hr
      .info-wrapper data-controller='tagify' data-action='turbolinks:before-cache@window->tagify#teardown' data-tagify-url==api_v1_meta_data_tags_path
        = f.input :tag_list, label: t('new-story-form.tags'), input_html: { class: 'tagify--outside', placeholder: t('new-story-form.separate_tags_with_space'), data: { tagify_target: 'tagInput' } }

      .info-wrapper
        = f.input :language_code, collection: fake_languages, label: t('new-story-form.language')

    . data-writer-navigation-target='chapters'
      = render 'chapters', story: @story if @updatable

app/views/writer/stories/_main.slim
- if !my_stories.present? || my_stories.empty?
  .workspace-nocontent
    = mi.shape(:library_books).css_class('nocontent-icon')
    p = t('writer_space.nocontent', fullname: current_user.fullname)

- format_my_stories(my_stories).map do |story|
  .sortable-item data-id==story[:id]
    .drag-indicator
      = mi.shape(:drag_indicator)
    .sortable-story
      .story-wrapper
        = image_tag story[:cover], class: 'story-cover'
        .story-info
          strong.story-name = story[:title]
          .story-chapters
            b.published-chapters
              = story[:published]
              = ' '
              = t('writer_space.chapters.published')
            = ' - '
            b.draft-chapters
              = story[:draft]
              = ' '
              = t('writer_space.chapters.draft')
          .story-updated
            = t('writer_space.updated')
            = ' '
            = story[:updated]
          .story-analysis
            .analysis-info
              = mi.shape(:visibility).css_class('analysis-icon')
              = story[:views]
            .analysis-info
              = mi.shape(:comment).css_class('analysis-icon')
              = story[:comments]
      .story-action
        = link_to edit_writer_story_path(story[:id]), class: 'writting-btn'
          | #{t('writer_space.continue_writing')}
          = mi.shape(:arrow_forward).css_class('writting-btn-icon')
        .action-group
          button.action-btn
            = mi.shape(:bar_chart).css_class('action-btn-icon')
            | #{t('writer_space.stats')}
          = link_to share_path(story[:id]), class: 'action-btn', data: { action: 'click->share-modal#open', turbo_stream: true } do
            = mi.shape(:share).css_class('action-btn-icon')
            | #{t('writer_space.share')}
          .dropdown
            button.action-btn
              = mi.shape(:more_horiz).css_class('action-btn-icon')
            .dropdown-list
              = button_to writer_story_path(story[:id]), class: 'dropdown-item', method: :delete, form: {data: { turbo_confirm: t('confirmation.stories.delete') } } do
                = mi.shape(:delete).md_18.css_class('action-btn-icon')
                = t('writer_space.delete')
              - if story[:is_published]
                = button_to unpublish_all_writer_story_path(story[:id]), class: 'dropdown-item', method: :patch, form: {data: { turbo_confirm: t('confirmation.stories.unpublish_all') } } do
                  = mi.shape(:unpublished).md_18.css_class('action-btn-icon')
                  = t('writer_space.unpublish')
              button.dropdown-item
                = mi.shape(:visibility).md_18.css_class('action-btn-icon')
                = t('writer_space.view_as_reader')

app/views/writer/stories/edit.html.slim
= render 'editable_form', story: @story, url: writer_story_path, preview_url: url_for(@story.cover_image), preview_filename: @story.cover_image.blob.filename, preview_filesize: @story.cover_image.blob.byte_size

app/views/writer/stories/index.html.slim
.writer-space
  .space-heading
    h1.writer-space-title = t('writer_space.title')
    = link_to new_writer_story_path, class: 'new-btn' do
      = mi.shape(:add).round.md_18
      | #{t('writer_space.new_story')}
  .workspace data-controller='workspace-navigation'
    .workspace-heading
      = link_to t('writer_space.published'), writer_stories_path, class: 'option-btn active', data: { action: 'click->workspace-navigation#published', workspace_navigation_target: 'publishedBtn' }
      = link_to t('writer_space.all_stories'), writer_stories_all_path, class: 'option-btn', data: { turbo_stream: true, action: 'click->workspace-navigation#all', workspace_navigation_target: 'allBtn' }

    #workspace-main.workspace-content.sortable-list data-controller='sortable' data-sortable-url==order_writer_story_path(':id')
      = render 'main', my_stories: @my_stories

app/views/writer/stories/new.html.slim
= render 'editable_form', story: @story, url: writer_stories_path