config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  get 'up' => 'rails/health#show', as: :rails_health_check

  namespace :api do
    namespace :v1 do
      resources :example, only: [:index, :show]
      namespace :meta_data do
        get 'tags'
      end
    end
  end

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  available_locales = -> { I18n.available_locales.map(&:to_s).join('|') }
  scope '(:locale)', locale: Regexp.new(available_locales.call) do
    namespace :auth do
      get 'sign-in'
      get 'sign-up'
    end

    get 'share/:id' => 'share#index', as: :share

    resources :profiles, only: [:index, :show]

    namespace :writer do
      namespace :stories do
        get 'all'
      end
      resources :stories, except: [:show] do
        member do
          patch :order
          patch :unpublish_all
        end
        resources :chapters, except: [:new, :show] do
          member do
            patch :order
            patch :publish
            patch :unpublish
          end
        end
      end
    end

    resources :stories, only: [:index, :show] do
      resources :chapters, only: [:show] do
        member do
          get :rephrase
          get :translate
          get :rephrase_alt
          get :summarize
        end
        resources :comments, except: [:update] do
          get :reply
        end
      end
    end

    root 'home#index'
  end
end

app/views/shared/_footer.slim
footer.footer
  .footer-container
    p.footer-heading
      = t('footer.heading')
    p.footer-text
      = t('footer.description')
      br
      = t('footer.description_continued')
    .footer-link-group
      = link_to t('footer.home'), root_path, class: "footer-link"
      = link_to t('footer.about'), '#about', class: "footer-link"
      = link_to t('footer.contact'), '#contact', class: "footer-link"
      = link_to t('footer.privacy_policy'), '#policy', class: "footer-link"
    .footer-social-icons
      = link_to "#", class: "footer-social-icon" do
        = mi.shape(:facebook)
    p.footer-bottom-text
      | &copy; 2024 Bilingo

app/views/shared/_mobile_sidebar.slim
.mobile-sidebar data-navbar-target=data_navbar_target data-controller='mobile-sidebar'
  .sidebar-dropdown
    .dropdown-btn data-mobile-sidebar-target='dropdownBtn'
      span = t('navbar.browse')
      = mi.shape(:arrow_downward).round.css_class('dropdown-icon')
    .dropdown-list data-mobile-sidebar-target='dropdownList'
      .dropdown-item
        .genres
          b.genres-title = t('navbar.genres')
          .genres-list
            - all_genres.each do |genre|
              = link_to genre.name
      .dropdown-item
        .topic
          b.topic-title = t('navbar.trending_topics')
          .topic-list
            - all_topics.each do |topic|
              = link_to topic

  .sidebar-dropdown
    .dropdown-btn
      span = t('navbar.community')
      = mi.shape(:arrow_downward).round.css_class('dropdown-icon')

  .sidebar-dropdown
    .dropdown-btn data-mobile-sidebar-target='dropdownBtn'
      span = t('navbar.write')
      = mi.shape(:arrow_downward).round.css_class('dropdown-icon')
    .dropdown-list data-mobile-sidebar-target='dropdownList'
      .dropdown-item
        = link_to new_writer_story_path, class: 'writer' do
          = inline_svg_tag 'icons/writer_icon.svg'
          .writer-title = t('navbar.write_new_story')
      .dropdown-item
        = link_to writer_stories_path, class: 'writer' do
          .writer-title = t('navbar.my_stories')

app/views/shared/_navbar.slim
header.sticky.top-0.z-max data-controller='navbar'
  nav.navbar-container
    .navbar-group__left
      = link_to t('navbar.title'), root_path, class: 'navbar-link navbar-title'
      .dropdown
        .dropdown-btn
          .navbar-link.write-btn
            = t('navbar.browse')
        .dropdown-list.browse-dropdown
          .dropdown-list-wrapper
            h1 = t('navbar.genres')
            .dropdown-list-genre
              - all_genres.each do |genre|
                = link_to genre.name
          .dropdown-list-wrapper
            h1 = t('navbar.trending_topics')
            .dropdown-list-topic
              - all_topics.each do |topic|
                = link_to topic

    .search-box
      = form_with url: '#search', method: :get, class: 'search-form' do |f|
        = f.button :button, type: :submit, class: 'search-btn' do
          = inline_svg_tag 'icons/search_icon.svg'
        = f.text_field :query, class: 'search-input', placeholder: t('navbar.search')

    .navbar-group__right
      .dropdown
        .dropdown-btn
          .navbar-link.write-btn
            = t('navbar.write')
            = mi.shape(:arrow_drop_down).md_18
        .dropdown-list.write-list
          .dropdown-item
            = link_to new_writer_story_path, class: 'writer navbar-link' do
              = inline_svg_tag 'icons/writer_icon.svg'
              .writer-title = t('navbar.write_new_story')
          .dropdown-item
            = link_to writer_stories_path, class: 'writer navbar-link' do
              .writer-title = t('navbar.my_stories')

      - if user_signed_in?
        .dropdown.profile-dropdown
          .dropdown-btn.user-profile
            span.avatar-text = current_user.last_name.first
          .dropdown-list.profile-list
            .dropdown-item
              = link_to profiles_path, class: 'account-option' do
                = mi.shape(:account_circle).md_18
                = t('navbar.user_profile')
            .dropdown-item
              = link_to '#setting', class: 'account-option' do
                = mi.shape(:settings).md_18
                = t('navbar.settings')
            .px-2.my-1
              .border-b.w-full
            .dropdown-item
              = button_to destroy_user_session_path, method: :delete, class: 'account-option' do
                = mi.shape(:logout).md_18
                = t('navbar.logout')
      - else
        = link_to t('navbar.sign_in'), auth_sign_in_path, class: 'navbar-link sign-in-btn', data: { action: 'click->auth-modal#open', turbo_stream: true }
        = link_to t('navbar.sign_up'), auth_sign_up_path, class: 'navbar-link sign-up-btn', data: { action: 'click->auth-modal#open', turbo_stream: true }

      .mobile-menu-btn data-navbar-target='mobileMenu'
        = mi.shape(:menu).round

      .h-6.border-l.mx-2

      .dropdown.localization-dropdown
        .dropdown-btn
          .navbar-link.localization-btn
            span = current_locale
            = mi.shape(:arrow_drop_down).md_18
        .dropdown-list.localization-list
          - locales.map do |locale|
            .dropdown-item
              = link_to({ locale: locale[:code] }, { class: 'localization navbar-link' }) do
                = inline_svg_tag locale[:flag], class: 'locale-icon'
                span = "#{locale[:name]} (#{locale[:code].upcase})"
                = mi.shape(:check).round.md_18.css_class('text-green-600') if current_locale.to_s.downcase == locale[:code].to_s.downcase

  = render 'shared/mobile_sidebar', data_navbar_target: 'mobileSidebar'