config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  get 'up' => 'rails/health#show', as: :rails_health_check

  namespace :api do
    namespace :v1 do
      resources :example, only: [:index, :show]
      namespace :meta_data do
        get 'tags'
      end
    end
  end

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  available_locales = -> { I18n.available_locales.map(&:to_s).join('|') }
  scope '(:locale)', locale: Regexp.new(available_locales.call) do
    namespace :auth do
      get 'sign-in'
      get 'sign-up'
    end

    get 'share/:id' => 'share#index', as: :share

    resources :profiles, only: [:index, :show]

    namespace :writer do
      namespace :stories do
        get 'all'
      end
      resources :stories, except: [:show] do
        member do
          patch :order
          patch :unpublish_all
        end
        resources :chapters, except: [:new, :show] do
          member do
            patch :order
            patch :publish
            patch :unpublish
          end
        end
      end
    end

    resources :stories, only: [:index, :show] do
      resources :chapters, only: [:show] do
        member do
          get :rephrase
          get :translate
          get :rephrase_alt
          get :summarize
        end
        resources :comments, except: [:update] do
          get :reply
        end
      end
    end

    root 'home#index'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @stories = Story.includes([:author, :chapters, { cover_image_attachment: :blob }, :primary_genre, :secondary_genre]).with_published.limit(5)
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def format_stories(stories)
    stories.map do |story|
      {
        cover: story.cover_image,
        title: story.name,
        author: story.author.fullname,
        description: story.description,
        genres: story.genres.join(' / '),
        views: story.views,
        comments: '15K',
        chapters: story.chapters.size,
        url: story_path(story),
        share: share_path(story)
      }
    end
  end
end

app/views/home/_carousel.slim
.carousel.hidden data-controller='carousel'
  - fake_top_story.map do |story|
    .slider-wrapper
      .backdrop-fill.blur-background
        = image_tag story[:cover], class: 'backdrop-img', width: 220
      .backdrop-fill.fill-background
      .slider-item
        .book-info
          h1.book-title = story[:title]
          .book-analysis
            .counter
              = mi.shape(:visibility).outlined.md_18
              = story[:views]
            .counter
              = mi.shape(:comment).outlined.md_18
              = story[:comments]
            .counter
              = mi.shape(:format_list_bulleted).outlined.md_18
              = story[:chapters]

          p.book-description
            b = t('carousel.description')
            br
            == story[:description]

          = link_to t('carousel.reading'), '#read', class: 'reading-btn'
        = image_tag story[:cover], class: 'book-cover', width: 220

app/views/home/_justview.slim
.story-list
  h1.story-heading = t('just_view_story_list.heading')
  - fake_top_story.map do |story|
    .view-story-book
      .story-cover-wrapper
        .backdrop-fill.blur-background
          = image_tag story[:cover], class: 'backdrop-img'
        .backdrop-fill.fill-background
        = image_tag story[:cover], class: 'book-cover'

      = link_to '#story-1' do
        h1.story-title = story[:title]

      = link_to '#story-1' do
        p.story-description = story[:description].truncate_words(20)

      .story-controls
        = link_to '#story-1-share', class: 'read-btn' do
          span = t('story.reading_now')
          = mi.shape(:chevron_right).md_18

app/views/home/_stories.slim
.stories
  = render 'storylist'
  = render 'justview'

app/views/home/_storylist.slim
.story-list
  h1.story-heading = t('story_list.heading')
  - format_stories(@stories).map do |story|
    .story-book
      .book-cover-wrapper
        = link_to story[:url] do
          = image_tag story[:cover], class: 'book-cover'
      .book-info
        = link_to story[:url] do
          strong.book-title = story[:title]
        .book-author
          i = t('story_list.by')
          | &nbsp;
          i = link_to story[:author], '#story-1-author'
        = link_to story[:url] do
          p.book-description == story[:description].truncate_words(40)
        small.book-meta
          = "#{story[:genres]} • #{story[:chapters]} #{t('story_list.chapters')}"
        .sharing
          = link_to story[:share], data: { turbo_stream: true, action: 'click->share-modal#open' }, class: 'facebook-btn' do
            = mi.shape(:share).outlined
          = link_to '#story-1-flag', class: 'flag-btn' do
            = mi.shape(:flag).outlined
        = link_to story[:url], class: 'read-btn' do
          span = t('story.reading_now')
          = mi.shape(:chevron_right).md_18
  - if @pagy && @pagy.pages > 1
    == pagy_nav(@pagy)
  - else
    hr
    = link_to stories_path, class: 'more-btn' do
      = t('story_list.more_btn')
      = mi.shape(:chevron_right).md_18

app/views/home/index.html.slim
= render 'carousel'
= render 'stories'